version: '3.8'

services:
  agent_api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: agent_api
    restart: "no"
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
