version: '3.8'

services:
  agent_api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: agent_api
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5434/secure_aadhaar
      - CELERY_BROKER_URL=pyamqp://queue_user:x54321@rabbit_mq//
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:password@host.docker.internal:5434/secure_aadhaar
    extra_hosts:
      - "host.docker.internal:172.17.0.1"