ssr:
  description: >
    "{customer} reached out with a critical inquiry:
    {inquiry}

    {person} from {customer} is seeking support. 
    Use all available resources, including warranty terms, 
    to provide a complete and accurate response."
  expected_output: >
    A detailed, informative response addressing all aspects of the inquiry.
    Reference all sources, including external data or documentation.
    Ensure the response is comprehensive, well-structured, and maintains a friendly tone.

sqar:
  description: >
    Review the response drafted by the Senior Support Representative for {customer}'s inquiry. 
    Ensure that the answer is comprehensive, accurate, and adheres to the 
    high-quality standards expected for customer support.

    Verify that all parts of the customer's inquiry have been addressed 
    thoroughly, with a helpful and friendly tone.

    Check for references and sources used to find the information, 
    ensuring the response is well-supported and leaves no questions unanswered.
  expected_output: >
    A final, detailed, and informative response ready to be sent to the customer.
    This response should fully address the customer's inquiry, incorporating all 
    relevant feedback and improvements.

    Maintain a professional but friendly tone throughout.
